### PR TITLE
Update the bot profile in Chinese #1

### PR DESCRIPTION
**Pull request by chusiang**
Hi, Junichi Ito:

I have update the some record of Chinese at `lib/tasks/insert_tw.rake`,
and I create a [HipChat room](https://www.hipchat.com/gF6ytBpJ6) to integrate the Tweets and GitHub.
 
Thank you for your help.

### CODE REVIEW

**Comment by JunichiIto** [comment]
@chusiang I will update production database later.

**Comment by JunichiIto** [comment]
@chusiang I ran the script against the staging environment. Could you check if the data is correct? 
http://bevimmer-staging.herokuapp.com/?lang=tw

**Comment by chusiang** [comment]
I have review it, the correct data is right. :)

**Comment by JunichiIto** [comment]
Thanks, I updated the production environment.
http://bevimmer.herokuapp.com/?lang=tw

**Comment by chusiang** [comment]
Thank you very much.
ほんとうにありがとうございました。

**Comment by JunichiIto** [comment]
不用謝！

**Pull request merged**
