### PR TITLE
Update the bot profile in Chinese #2

### PR DESCRIPTION
**Pull request by chusiang**
Hi, Junichi Ito:

I have update the some record at lib/tasks/insert_tw.rake,
and create a README.zh-TW.rdoc.

### CODE REVIEW

**Comment by JunichiIto** [comment]
@chusiang Okay, but it might take a few days until merged. 请等一下。

**Comment by chusiang** [comment]
That's OK, thank you.

**Comment by JunichiIto** [comment]
@chusiang Hi, I updated the commands. Please review them.
http://bevimmer.herokuapp.com/?lang=tw

**Comment by chusiang** [comment]
@JunichiIto I have reviewed it, that's OK.

**Pull request merged**
